#include "Cast.hpp"

int main() {
  cout << "////////////////////////////\n";
    Cast t1("0");
    cout << "0 : \n";
    t1.getStatus();
  cout << "***\n";
    t1.resault();
  cout << "////////////////////////////\n";
    Cast t2("65");
    cout << "65 : \n";
    t2.getStatus();
  cout << "***\n";
    t2.resault();
  cout << "////////////////////////////\n";
    Cast t3("a");
    cout << "a : \n";
    t3.getStatus();
  cout << "***\n";
    t3.resault();
  cout << "////////////////////////////\n";
    Cast t4("555");
    cout << "555 : \n";
    t4.getStatus();
  cout << "***\n";
    t4.resault();
  cout << "////////////////////////////\n";
    Cast t5("9.8f");
    cout << "9.8f : \n";
    t5.getStatus();
  cout << "***\n";
    t5.resault();
  cout << "////////////////////////////\n";
    Cast t6("9.8");
    cout << "9.8 : \n";
    t6.getStatus();
  cout << "***\n";
    t6.resault();
  cout << "////////////////////////////\n";
    Cast t7("5454654654654654564");
    cout << "5454654654654654564 : \n";
    t7.getStatus();
  cout << "***\n";
    t7.resault();
  cout << "////////////////////////////\n";
    Cast t8("+inff");
    cout << "+inff: \n";
    t8.getStatus();
  cout << "***\n";
    t8.resault();
  cout << "////////////////////////////\n";
    Cast t9("nan");
    cout << "nan: \n";
    t9.getStatus();
  cout << "***\n";
    t9.resault();
  cout << "////////////////////////////\n";
    Cast t10("trash");
    cout << "trash: \n";
    t10.getStatus();
  cout << "***\n";
    t10.resault();
  cout << "////////////////////////////\n";
    Cast t11("trash10");
    cout << "trash10: \n";
    t11.getStatus();
  cout << "***\n";
    t11.resault();
  cout << "////////////////////////////\n";
    Cast t12("10trash");
    cout << "10trash: \n";
    t12.getStatus();
  cout << "***\n";
    t12.resault();
  cout << "////////////////////////////\n";
}
