# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: orahmoun <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/22 10:46:58 by orahmoun          #+#    #+#              #
#    Updated: 2022/03/22 10:47:54 by orahmoun         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#		VARS	:

CFLAGS 	= 	-Wall -Wextra -Werror

STD 		=		-std=c++98

CC	 		=		c++

SRC 		=		megaphone.cpp

#		RULES	:

all	:	$(SRC)
		$(CC) $(CFLAGS) $(STD) $(SRC) -o megaphone
